# import tkinter
# from tkinter import messagebox
# app=tkinter.Tk()
# def data():
#     # print(v1.get())
#     # v=v1.get()
#     # l2.config(text=v)
#     # messagebox.showinfo("display",v1.get())
#     # messagebox.askokcancel("display",v1.get())
#     # messagebox.askquestion("display",v1.get())
#     # messagebox.askretrycancel("display",v1.get())
#     # messagebox.askyesnocancel("display",v1.get())
#     # print(v_c1.get())
#     # print(v_c2.get())
#     if v_c1.get()==1:
#         print("mal selected")
#     if v_c2.get()==2:
#         print("eng selected")
#         print(vr1.get())   
# app.title("synnefo")
# app.minsize(400,400)
# app.maxsize(600,600)
# app.config(bg="black")
# l1=tkinter.Label(app,text="welcome",bg="black",fg="red")
# l1.pack()
# v1=tkinter.StringVar()
# e1=tkinter.Entry(app,textvariable=v1)
# e1.pack()
# v_c1=tkinter.IntVar()
# v_c2=tkinter.IntVar()
# # v_c1=tkinter.StringVar(value="mal")
# # v_c2=tkinter.StringVar(value="eng")
# c1=tkinter.Checkbutton(app,text="mal",variable=v_c1)
# c1.pack()
# c2=tkinter.Checkbutton(app,text="eng",variable=v_c2)
# c2.pack()
# vr1=tkinter.IntVar()
# r1=tkinter.Radiobutton(app,text="male",value=1,variable=vr1)
# r2=tkinter.Radiobutton(app,text="female",value=2,variable=vr1)
# r1.pack()
# r2.pack()
# b1=tkinter.Button(app,text="save",bg="blue",fg="white",activebackground="green",activeforeground="pink",padx=10,pady=20,command=data)
# b1.pack()
# l2=tkinter.Label(app)
# l2.pack()
# app.mainloop()



import tkinter
app=tkinter.Tk()
c=tkinter.Canvas(app,width=400,height=400,bg="red")
c.create_line(0,150,350,150)
c.create_rectangle(50,50,350,250,fill="green")
c.create_oval(50,50,350,250,fill="black")
c.pack()
app.mainloop()